### ISSUE TITLE
This extension is not serial monitor, it is serial opener.

### ISSUE THREAD

**Issue by kplese** [microsoft/vscode-serial-monitor#105]
So, I want to monitor serial data, not open port so that the application I would like to monitor cannot open the port.

**Comment by gcampbell-msft** [comment]
@kplese I'm not sure I fully understand your feedback, are you requesting that the Serial Monitor allow you to read the data from your own extension? 

The goal of this extension is to provide a very easy-to-use Serial Monitor that allows you to monitor a port and view it's output with various options like timestamps. Are there other goals that you're trying to accomplish with this extension?

**Comment by gcampbell-msft** [comment]
@kplese Understood. Thanks for your feedback!

However, the goal of this extension is to provide a Serial Monitor with great UI that allows users to monitor the COM port communication, as well as read/write. The extension accomplishes both. I understand that the API that is surfaced from this extension does act more like a "Serial Opener", as the goal of the API is to make it easier for other extensions to pop open a Serial Monitor, which makes it easier for users to open and interact with the monitor. 

However, this extension isn't designed to support the ability of _other extensions_ to use the API in order to monitor the data stream of the COM port.

Thanks again for your feedback! Closing this issue.
