### ISSUE TITLE
Connect Windows COM port while running on WSL2

### ISSUE THREAD

**Issue by FH0** [microsoft/vscode-serial-monitor#122]
I flash firmware on WSL2 using something like `./tools/linux/SocToolKit/bin/windows/upgrade_tool.exe`. So I can make it work without `usbipd wsl attach`.

It would be better for me to connect Windows COM port while running on WSL2.

**Comment by gcampbell-msft** [comment]
Hi, @FH0 I'm not sure I fully understand your request. You mention that you are using WSL2 and some things regarding that, and then you mention moving the items inside the red square.

Could you more clearly define your request? If there are multiple, please make a separate issue for each. 

Thanks!

**Comment by gcampbell-msft** [comment]
Hi, @FH0, in a WSL2 command-line, are you able to enumerate the Windows COM ports?

**Comment by FH0** [comment]
```bash
root@H610ITX /root
# /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe "Get-WmiObject Win32_PnPEntity -Filter \"Name LIKE 'USB-SERIAL%'\" | Select Name"

Name
----
USB-SERIAL CH340 (COM6)
USB-SERIAL CH340 (COM5)
USB-SERIAL CH340 (COM10)
```

**Comment by gcampbell-msft** [comment]
@FH0 Based on your output, it seems like you actually accessed Windows powershell and actually directly got the serial ports from windows, rather than from WSL. This means that it actually ran in Windows, not WSL. 

Are you able to use any of the strategies, from, for example, https://www.cyberciti.biz/faq/find-out-linux-serial-ports-with-setserial/, to get the ports from WSL?

**Comment by FH0** [comment]
I have no idea about it. I will use `usbipd wsl attach`. Thanks for your help.
