### ISSUE TITLE
Add filter for Output

### ISSUE THREAD

**Issue by Zxis233** [microsoft/vscode-serial-monitor#138]
As is said in the title, could you please add the filter to ignore some unuseful output for a clean view?

**Comment by gcampbell-msft** [comment]
Thanks for your request, @Zxis233 ! However, this isn't currently something that we are interested in (or have bandwidth) to implement. Our suggestion would be to filter any output on the other side, so that only data that you're interested in comes to the Serial Monitor. 

Thanks! Closing this as Won't Fix.
