### ISSUE TITLE
Support for releasing and reconnecting to ports in coordination with build tools

### ISSUE THREAD

**Issue by jmbldwn** [microsoft/vscode-serial-monitor#140]
Type: Feature Request

Embedded systems often use the same port for debugging and uploading new builds.  Arduino works this way, but it's not the only case.

This creates a contention between the uploader and the monitor.  We need to release the serial port in the monitor before we upload, then reconnect it after.  It's easy to get out of sync and have a failed upload because the serial port is not released, or miss the early output of the new build because I didn't get the monitoring started again quickly.

The Arduino environment handles this in its IDE by coordinating between builds and its serial monitor, but if you don't use their IDE (why would you when you have VSCode and command-line build tools?) you are out of luck.

The proposal:  let me identify a file that acts as a mutex between the serial monitor and whatever build tools I'm using.  This file would contain a javascript timestamp that could easily be written by my build tools as a step during the "make upload" workflow/scripts (or whatever).  

The existence of the file is how the build tools indicate they want to use the serial port.  The serial monitor would, when it sees this file change or come into existence, release the serial port until the file is removed, whereupon it would attempt to start monitoring again.

The reason for the timestamp in the mutex file is to facilitate cleanup.  If the timestamp is not fresh it's probably from a previously-aborted upload and the file could be ignored.  Normally the uploader would just remove the file after its done.

These files would be defined per-serial port, of course, so if we need to we can coordinate multiple ports independently.

Not trying to over-specify the "how" here.  If it's a simple file its easier to build scripting into the tool chain to use it, but any mechanism I can control from a script/makefile would be fine.

You could assume the build is happening in a VSCode terminal window, but I think it'd be more flexible if this mechanism didn't depend on that.

**Comment by gcampbell-msft** [comment]
@jmbldwn Thank you for posting this suggestion / request. I apologize for taking so long to respond to this. 

We have a [Serial Monitor API](https://www.npmjs.com/package/@microsoft/vscode-serial-monitor-api) that can be invoked from other VSCode Extensions. It is also described in the [ README of this repo](https://github.com/microsoft/vscode-serial-monitor#readme). 

Our suggestion is to create an extension that can do your desired mutex work, and utilize the Serial Monitor API to stop and start the port monitoring. 

As for putting it in our Serial Monitor extension, we view this as out of scope for this generic extension since there could be lots of different build systems and ways to detect using the port for uploading. 

Again, thank you for posting this idea! Closing as not planned.
