### ISSUE TITLE
Serial Monitor buttons does not appear anymore

### ISSUE THREAD

**Issue by meinblickfang** [microsoft/vscode-serial-monitor#154]
Hi,
since 2 days, the serial monitor button does not exists anymore. Deinstalled Extension and reinstalled. 

Beside the buttons in the panel Terminal / Debug console / comments -- the serial monitor button does not exists anymore. I would be very happy if you can give me a hint to get access to the serial monitor again...

Thanks!
Daniel
![CleanShot 2023-12-18 at 21 39 33@2x](https://github.com/microsoft/vscode-serial-monitor/assets/6604833/084740e7-6876-4a6f-9232-cbf3b913e6c7)

**Comment by meinblickfang** [comment]
I found it. It has been moved to the left main nav bar and was not accesible in the initial panel where terminal etc was..

**Comment by gcampbell-msft** [comment]
A couple of questions, are you able to tell if the extension activated? Also, could you do some small testing to identify whether there is a specific version that this starts happening on? 

Here are a couple of possible things to try to fix this: 
1. Run the `Serial Monitor: Focus on Serial Monitor View` command and see what happens. 
2. Run the `Serial Monitor: Reset Serial Monitor Windows` command. 

I made sure just now to update the extension and attempt to reproduce this, but I am able to see the Serial Monitor view and open it, and it works as expected. Any information you could provide would be helpful so that we can get you back up and running using the Serial Monitor extension! 

Another thing that could help us investigate is: what OS are you on?
