### ISSUE TITLE
We need custom baudrate！

### ISSUE THREAD

**Issue by Shawn-Tao** [microsoft/vscode-serial-monitor#166]
The 460800, 921600 or higher  baudrates are common, and used by many sensors。
But this tool only supports no more than 250000 baudrate, which hugely limitate its generality!

I hope the generous author will add higher baud rate support as soon as possible, or support for custom baud rates!

love you for your providing such a great tool!

**Comment by gcampbell-msft** [comment]
@Shawn-Tao We actually currently have support for custom baud rates! 

See the `vscode-serial-monitor.customBaudRates` setting. You can provide your own custom set of baud rates. 

Thanks! I'll close this issue since it's already supported, but please let me know if there is still something missing.
