### ISSUE TITLE
Failed to open the serial port /dev/ttyACM1

### ISSUE THREAD

**Issue by tapir** [microsoft/vscode-serial-monitor#174]
Type: Bug Report

**Describe the bug**
- OS and Version: Debian 12
- VS Code Version: 1.87.2
- Serial Monitor Extension Version: Both 0.11 and v0.11.240326001 tested
- Target embedded device: ESP32-C3 
- Other extensions you installed (and if the issue persists after disabling them): Arduino, Docker, Go, C++ and yes it persists
- A clear and concise description of what the bug is.

When I'm trying to open serial console for /dev/ttyACM1 I get an error saying **** Failed to open the serial port /dev/ttyACM1 ****
Couple things to help
- I have the correct udev rules in place, all my ttyACM devices are part of group dialout and my user is also part of group dialout.
- VSCode-arduino can successfully upload sketches through the same interface nor do I have any other application complaining about it so it's not a permission issue.

**Comment by ToonVanEyck** [comment]
This is the same as #142.

**Comment by gcampbell-msft** [comment]
@tapir Closing this issue in favor of #142 

However, Because I've noticed that the bug here on the external dependency: https://github.com/serialport/node-serialport/issues/2636, is only happening on linux, I wonder if a quick way to unblock you all is to only call this method if we're not on linux. 

Could you all manually switch the extension of this zip to .vsix, install it, and test to see if this fixes your issue? 
[vscode-serial-monitor.zip](https://github.com/microsoft/vscode-serial-monitor/files/14852978/vscode-serial-monitor.zip)
