### ISSUE TITLE
Feature Request: When the received message is displayed, the part beyond the page is automatically moved to the next line

### ISSUE THREAD

**Issue by xiaguangbo** [microsoft/vscode-serial-monitor#19]
Messages that are currently out of page require manual movement of the bottom slider to see the remainder：
There is another problem here, the page slider is moved to the far right and still some parts are not fully displayed, you can only see all the message by adjusting the page size to exceed the length of the message
<img width="619" alt="image" src="https://user-images.githubusercontent.com/102402151/175030756-6499f2a3-4734-4a05-9159-4bb2b8c52e7b.png">

When the terminal(Powershell embedded in vscode) displays text, it will automatically adjust the character display position according to the page size, such as the yellow characters in the figure. This eliminates the need for a page slider：
<img width="457" alt="image" src="https://user-images.githubusercontent.com/102402151/175030938-1eb774aa-c01c-40a5-86f0-44e330d6be8e.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/102402151/175031108-bcb40c5f-be91-4434-9e09-c59be7677041.png">

**Comment by gcampbell-msft** [comment]
@xiaguangbo I believe this may have been fixed by the solution to #17, which is available in pre-release, please let me know if that is the case! 

As for the feature request, we'll deliberate whether it can fit into our backlog, but the issue where things don't show up without resizing the window should be fixed. Thanks for letting us know!
