### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by JackHerRrer** [microsoft/vscode-serial-monitor#44]
Type: Feature Request

It would be great if syntax hilighting was available in the serial monitor. This is usually realy helpfull when reading logs.
Thanks

**Comment by gcampbell-msft** [comment]
@JackHerRrer Am I correct to assume that this is a related request to #4, #42, #11 ?

**Comment by gcampbell-msft** [comment]
@JackHerRrer Ah, that helps a lot. Thanks for the explanation.

I should note that the reason that the "VSCode Log Output Colorizer" isn't compatible with our extension is because that extension is specifically for things that show up on Output panes, while our extension is its own view. 

Either way, I'll mark this as an enhancement request and we will take stock of the backlog and see if/where it fits. 

Thanks for the feedback!

**Comment by robotdad** [comment]
We've discussed this in more depth, per @gcampbell-msft comment above the output colorizer isn't compatible with our view as we aren't an output pane. We're also considering some other changes to our view at the moment that would further complicate satisfying this request. As such we're not going to pursue this.
