### ISSUE TITLE
Allow a different background color for the terminal window

### ISSUE THREAD

**Issue by SamBozman** [microsoft/vscode-serial-monitor#49]
Because all of my VSCode is in a dark theme it sometimes is difficult to distinguish the terminal and related windows against the whole project. It would be nice if a user could change the background color of these blocks of related problem solving windows to make it easier to instantly realize that a terminal or serial monitor...etc window is hiding the code.
Thanks for listening.
Sam Bozman

**Comment by gcampbell-msft** [comment]
@SamBozman Hi Sam, thanks for the feedback! 

I believe this is more of an issue on core VSCode, rather than simply our extension, as this request applies to all of VSCode extensions, output panes, custom views, etc. 

Could you please move this issue to the vscode repo issues list? https://github.com/microsoft/vscode/issues
