### ISSUE TITLE
Broken Serial Monitor v0.8.0 for Remote Development over SSH

### ISSUE THREAD

**Issue by ekawahyu** [microsoft/vscode-serial-monitor#77]
My VSCode just got an auto-update from v0.7.0 to v0.8.0 overnight (like about 19 hours ago). Local development seems to work just fine, but remote development over SSH does not seem to work at all. Rebooting both local and remote machines don't seem to fix any issue. There was no error message showed up. The only symptom that I can report here, is that whenever I use VSCode for remove development, Serial Monitor does not show serial devices on my remote device. It shows my local serial devices.

Please let me know if you need further info. Thank you.

**Comment by benmcmorran** [comment]
Can you try adding this to your `settings.json`? We made a change in 0.8.0 to prefer running the extension locally under the assumption that users are typically connecting to local embedded devices, but you can always override that preference with VS Code's `remote.extensionKind`.

```json
  "remote.extensionKind": {
    "ms-vscode.vscode-serial-monitor": [
      "workspace"
    ]
  },
```

**Comment by ekawahyu** [comment]
@benmcmorran I think the new feature for having local serial monitor is great! This would open up possibility to have cloud development environment, download the binary to local device, monitor it locally. But on the other hand, I am running a headless machine in the office, and this setup requiring serial monitoring on the same machine. I know it is out of topic of this issue, I can open another ticket for this, but would it be nice to have both local and remote ports available without requiring to switch?

Ok, so, adding those lines in `settings.json` works as intended. I also tried to switch between `ui` and `workspace` on the fly, but it does not seem to work unless I reboot my machine. Is this expected? Or is there anything else missing in my setup?

My machine is Apple M1. Please let me know if you need anything else from my end. Thank you.

**Comment by benmcmorran** [comment]
Glad it worked for you! Feel free to open a separate ticket for the feature request for simultaneous local and remote monitoring. I'll mention up front that it will likely be architecturally difficult to pull off given how VS Code runs extensions internally. VS Code extensions are for the most part unaware of if they are running locally or remotely, and VS Code manages setting up communication channels back to the UI if the extension is remote, so to do both at the same time would require that the extension itself knows how to set up these channels. That said, if there's enough community interest in the feature, we can certainly consider adding it.

I'm a bit surprised that you have to restart your entire machine to get the `settings.json` changes to take effect, but I'm also not on expert on how VS Code manages the extension lifecycle. Can you try running the "Developer: Reload Window" command from the command palette instead after changing `settings.json` and see if you get the expected behavior? My understanding is that that command will restart the extension host for all extensions.

**Comment by ekawahyu** [comment]
Yes, `Developer: Reload Window` solution works.

I tried to completely exit from VSCode and reopen, but that does not seem to work. Very persistent, hence rebooting the machine was the only way. Why would it need a reboot?

**Comment by axel-lebourhis** [comment]
Hi, I'm in the exact same situation than @ekawahyu, I'm working remotely on a machine in the office which has all my targets hooked up to it. I was about to go crazy trying to figure out why I couldn't connect to any port on this remote, glad I found this ticket.
Still, I'm wondering if prefering local monitoring is really adequat, I don't know if cloud development environment is that widely used in the embedded domain compared to just remote debugging.

**Comment by ToonVanEyck** [comment]
Is there a solution for VS code dev containers? I'm getting a blanco tab in my devcontainer.

**Comment by gcampbell-msft** [comment]
@ToonVanEyck I don't believe there would be natural support for dev containers, unless the ports are available on your devcontainer. Could you expand on what you are seeing?

**Comment by ToonVanEyck** [comment]
The ports are available both in the devcontainer (right) and in wsl (left)
![image](https://github.com/microsoft/vscode-serial-monitor/assets/24410099/7c61fa9c-8e98-448d-86e9-17ece895a8da)

But the extension doesn't work in the devcontainer (left)
![image](https://github.com/microsoft/vscode-serial-monitor/assets/24410099/55a2a891-f040-406c-af8c-0e2ea42ca552)

**Comment by gcampbell-msft** [comment]
@ToonVanEyck Have you attempted different settings of 

```
  "remote.extensionKind": {
    "ms-vscode.vscode-serial-monitor": [
      "workspace"
    ]
  },
```
?

**Comment by ToonVanEyck** [comment]
> @ToonVanEyck Have you attempted different settings of
> 
> ```
>   "remote.extensionKind": {
>     "ms-vscode.vscode-serial-monitor": [
>       "workspace"
>     ]
>   },
> ```
> 
> ?

I added that configuration to my settings.json and that allowed it to work under WSL. Before that configuration it only showed the Windows COM ports. But it didn't have an effect in the devcontainer.

**Comment by gcampbell-msft** [comment]
@ToonVanEyck Could you please open this in a new issue? This would help us evaluate it and make sure it doesn't get lost in this closed issue. Thanks!
