### ISSUE TITLE
Search via Control+F

### ISSUE THREAD

**Issue by wuhelong** [microsoft/vscode-serial-monitor#83]
Type: Feature Request

In version 0.7.0 and before, I can search by Control+F, but I can't do it after version. Hope it can be restored.

**Comment by gcampbell-msft** [comment]
@wuhelong Could you provide some screenshots or a gif? I just pulled down the 0.8.0 version and was not able to reproduce the Ctrl+F search being broken, it worked well for me. 

One thing to ensure is that you have clicked into the serial monitor view to ensure that the focus is in the terminal before pressing ctrl+f. 

Any context would be great so that we can try to reproduce. Thanks!

**Comment by wuhelong** [comment]
@gcampbell-msft Ok, please refer to the picture, I use macOS 13.2.1.
![s](https://user-images.githubusercontent.com/27722912/222707203-551249f7-03a1-40ce-903e-ae1ba37cae5c.gif)

**Comment by gcampbell-msft** [comment]
@wuhelong 
Based on some testing, I think the issue is based on not having the focus being on the Serial Monitor text view when you enter "Ctrl+F". Could you try clicking, and also highlighting, some text inside the text view to ensure that the focus is there, and then press ctrl+f? 

Please attach a video of you trying this out. Thanks for helping us diagnose this.

**Comment by wuhelong** [comment]
You should see a blinking cursor at the bottom of the screen, indicating where the focus is. Even if I let the focus be on the bottom "text input box" press Ctrl+F to get the same result.

**Comment by wuhelong** [comment]
Now it works fine I don't know why? The change I found was that before VS Code was not showing the local language. I don't know if there is an update installed. 

Also I use macOS. In other views of VSCode, I use cmd + F to start the search. But in Serial Monitor I need to use ctrl + F. In this way, it may not be easy for users to find out how to use the search.
