### ISSUE TITLE
Upon sending characters, send echo to the console

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#9]
Type: Feature Request

When sending characters, CR/LF can be added automatically, and the sent characters can also be displayed and recorded on the serial port console, which can better analyze the serial port interaction process

**Comment by gcampbell-msft** [comment]
@hongshui3000 I'm not sure I fully understand what your request is. 

Is it that when sending data to the port, you'd like to see a system message in the monitor reflecting this? Likely for the purpose of tracking when the data was sent to the port so that you can analyze the serial port interaction, like you said. Do I understand this correctly? 

Also, CR/LF can be added automatically in the current feature by utilizing the line ending dropdown.

**Comment by hongshui3000** [comment]
> @hongshui3000 I'm not sure I fully understand what your request is.
> 
> Is it that when sending data to the port, you'd like to see a system message in the monitor reflecting this? Likely for the purpose of tracking when the data was sent to the port so that you can analyze the serial port interaction, like you said. Do I understand this correctly?
> 
> Also, CR/LF can be added automatically in the current feature by utilizing the line ending dropdown.
> 
> Thanks!

yes

**Comment by hongshui3000** [comment]
works
