### ISSUE TITLE
921600 baud rate is not supported 

### ISSUE THREAD

**Issue by OoB-Services** [microsoft/vscode-serial-monitor#96]
Type: Feature Request

**Comment by gcampbell-msft** [comment]
Hi @OoB-Services !

We currently support the addition of "custom baud rates", which allow you to enter a custom list so that you can use more custom baud rates.

Could you try this and let us know if it works for you? 

Steps:
1. Navigate to the Serial Monitor settings in VSCode
![image](https://user-images.githubusercontent.com/86264750/233995943-2373db8b-66b4-4491-adf5-dd847814caa7.png)

2. Press `Add Item` in the `Custom Baud Rates` setting, and add 921600.
3. Navigate to the Serial Monitor and see the updated baud rate list.
![image](https://user-images.githubusercontent.com/86264750/233996099-1cb4ec37-4fd4-47d5-b246-ffe0a8090ddf.png)

**Comment by gcampbell-msft** [comment]
Closing this issue, since the custom baud rates are available, please let us know if you still hit any issues using 921600 as a baud rate!
